[package]
name = "pz5_editor"
version = "0.1.0"
authors = ["trionprog <trionprog@gmail.com>"]

[dependencies]
pz5 = { path = "../pz5" }
pz5_collada = { path = "../pz5_collada" }
glium = "*"
cgmath = "0.9.1"
glutin = "*"
